2025-08-11 14:31:56 - INFO - Will watch for changes in these directories: ['/Users/yang/PycharmProjects/vue-fastapi-admin']
2025-08-11 14:31:56 - INFO - Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
2025-08-11 14:31:56 - INFO - Started reloader process [27196] using WatchFiles
2025-08-11 14:31:57 - INFO - Started server process [27199]
2025-08-11 14:31:57 - INFO - Waiting for application startup.
2025-08-11 14:31:57.136 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:31:57.136 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:31:57 - INFO - Application startup complete.
2025-08-11 14:32:01 - INFO - 127.0.0.1:51096 - "GET /docs HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51139 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51140 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51142 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51143 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51144 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51145 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:32:05 - INFO - 127.0.0.1:51152 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 500 Internal Server Error
2025-08-11 14:32:05 - ERROR - Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 767, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 31, in __call__
    |     await response(request.scope, request.receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 178, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    |     await route.handle(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    |     await self.app(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    |     response = await func(request)
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/api/v1/points/points.py", line 229, in get_usage_records
    |     'id': record.id,
    |           ^^^^^^^^^
    | AttributeError: 'list' object has no attribute 'id'
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 31, in __call__
    await response(request.scope, request.receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 178, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/api/v1/points/points.py", line 229, in get_usage_records
    'id': record.id,
          ^^^^^^^^^
AttributeError: 'list' object has no attribute 'id'
2025-08-11 14:32:05 - INFO - 127.0.0.1:51154 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 500 Internal Server Error
2025-08-11 14:32:05 - ERROR - Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 767, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 31, in __call__
    |     await response(request.scope, request.receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 178, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    |     await route.handle(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    |     await self.app(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    |     response = await func(request)
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/api/v1/points/points.py", line 229, in get_usage_records
    |     'id': record.id,
    |           ^^^^^^^^^
    | AttributeError: 'list' object has no attribute 'id'
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 31, in __call__
    await response(request.scope, request.receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.11/3.11.13/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/core/middlewares.py", line 178, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yang/PycharmProjects/vue-fastapi-admin/app/api/v1/points/points.py", line 229, in get_usage_records
    'id': record.id,
          ^^^^^^^^^
AttributeError: 'list' object has no attribute 'id'
2025-08-11 14:33:48 - WARNING - WatchFiles detected changes in 'app/api/v1/points/points.py'. Reloading...
2025-08-11 14:33:48 - INFO - Shutting down
2025-08-11 14:33:48 - INFO - Waiting for application shutdown.
2025-08-11 14:33:48 - INFO - Application shutdown complete.
2025-08-11 14:33:48 - INFO - Finished server process [27199]
2025-08-11 14:33:49 - INFO - Started server process [28206]
2025-08-11 14:33:49 - INFO - Waiting for application startup.
2025-08-11 14:33:49.040 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:33:49.040 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:33:49 - INFO - Application startup complete.
2025-08-11 14:33:57 - INFO - 127.0.0.1:51347 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:33:57 - INFO - 127.0.0.1:51348 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:33:58 - INFO - 127.0.0.1:51349 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:33:58 - INFO - 127.0.0.1:51350 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:34:08 - INFO - 127.0.0.1:51402 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:34:08 - INFO - 127.0.0.1:51403 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:34:08 - INFO - 127.0.0.1:51404 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:34:08 - INFO - 127.0.0.1:51408 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:34:28 - INFO - 127.0.0.1:51447 - "GET /api/v1/points/usage/records?page=1&size=20&usage_type=service_consumption HTTP/1.1" 200 OK
2025-08-11 14:34:37 - INFO - 127.0.0.1:51460 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:35:07 - WARNING - WatchFiles detected changes in 'tests/test_usage_type_filter.py'. Reloading...
2025-08-11 14:35:07 - INFO - Shutting down
2025-08-11 14:35:07 - INFO - Waiting for application shutdown.
2025-08-11 14:35:07 - INFO - Application shutdown complete.
2025-08-11 14:35:07 - INFO - Finished server process [28206]
2025-08-11 14:35:08 - INFO - Started server process [28908]
2025-08-11 14:35:08 - INFO - Waiting for application startup.
2025-08-11 14:35:08.334 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:35:08.334 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:35:08 - INFO - Application startup complete.
2025-08-11 14:35:24 - WARNING - WatchFiles detected changes in 'tests/test_usage_type_filter.py'. Reloading...
2025-08-11 14:35:24 - INFO - Shutting down
2025-08-11 14:35:24 - INFO - Waiting for application shutdown.
2025-08-11 14:35:24 - INFO - Application shutdown complete.
2025-08-11 14:35:24 - INFO - Finished server process [28908]
2025-08-11 14:35:25 - INFO - Started server process [29042]
2025-08-11 14:35:25 - INFO - Waiting for application startup.
2025-08-11 14:35:25.451 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:35:25.451 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:35:25 - INFO - Application startup complete.
2025-08-11 14:35:43 - INFO - 127.0.0.1:51565 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:35:44 - INFO - 127.0.0.1:51566 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:35:44 - INFO - 127.0.0.1:51567 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:35:44 - INFO - 127.0.0.1:51568 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:36:13 - WARNING - WatchFiles detected changes in 'tests/create_test_usage_records.py'. Reloading...
2025-08-11 14:36:13 - INFO - Shutting down
2025-08-11 14:36:13 - INFO - Waiting for application shutdown.
2025-08-11 14:36:13 - INFO - Application shutdown complete.
2025-08-11 14:36:13 - INFO - Finished server process [29042]
2025-08-11 14:36:14 - INFO - Started server process [29473]
2025-08-11 14:36:14 - INFO - Waiting for application startup.
2025-08-11 14:36:14.247 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:36:14.248 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:36:14 - INFO - Application startup complete.
2025-08-11 14:36:28 - INFO - 127.0.0.1:51662 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:36:29 - INFO - 127.0.0.1:51664 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:36:29 - INFO - 127.0.0.1:51665 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:36:29 - INFO - 127.0.0.1:51666 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:37:04 - INFO - 127.0.0.1:51703 - "GET /api/v1/points/usage/records?page=1&size=20&usage_type=service_consumption HTTP/1.1" 200 OK
2025-08-11 14:37:14 - INFO - 127.0.0.1:51719 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:38:08 - INFO - 127.0.0.1:51777 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:38:08 - INFO - 127.0.0.1:51778 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:38:08 - INFO - 127.0.0.1:51779 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:38:09 - INFO - 127.0.0.1:51780 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:38:35 - INFO - 127.0.0.1:51806 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:38:35 - INFO - 127.0.0.1:51807 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:38:36 - INFO - 127.0.0.1:51808 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:38:36 - INFO - 127.0.0.1:51809 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:39:58 - WARNING - WatchFiles detected changes in 'tests/check_ag1_global_view_permission.py'. Reloading...
2025-08-11 14:39:58 - INFO - Shutting down
2025-08-11 14:39:58 - INFO - Waiting for application shutdown.
2025-08-11 14:39:58 - INFO - Application shutdown complete.
2025-08-11 14:39:58 - INFO - Finished server process [29473]
2025-08-11 14:39:59 - INFO - Started server process [31406]
2025-08-11 14:39:59 - INFO - Waiting for application startup.
2025-08-11 14:39:59.504 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:39:59.504 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:39:59 - INFO - Application startup complete.
2025-08-11 14:41:00 - WARNING - WatchFiles detected changes in 'tests/check_test_data_ownership.py'. Reloading...
2025-08-11 14:41:00 - INFO - Shutting down
2025-08-11 14:41:00 - INFO - Waiting for application shutdown.
2025-08-11 14:41:00 - INFO - Application shutdown complete.
2025-08-11 14:41:00 - INFO - Finished server process [31406]
2025-08-11 14:41:01 - INFO - Started server process [31965]
2025-08-11 14:41:01 - INFO - Waiting for application startup.
2025-08-11 14:41:01.176 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:41:01.176 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:41:01 - INFO - Application startup complete.
2025-08-11 14:41:36 - WARNING - WatchFiles detected changes in 'tests/create_admin_test_record.py'. Reloading...
2025-08-11 14:41:36 - INFO - Shutting down
2025-08-11 14:41:36 - INFO - Waiting for application shutdown.
2025-08-11 14:41:36 - INFO - Application shutdown complete.
2025-08-11 14:41:36 - INFO - Finished server process [31965]
2025-08-11 14:41:37 - INFO - Started server process [32337]
2025-08-11 14:41:37 - INFO - Waiting for application startup.
2025-08-11 14:41:37.322 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:41:37.322 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:41:37 - INFO - Application startup complete.
2025-08-11 14:41:52 - INFO - 127.0.0.1:52303 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:41:52 - INFO - 127.0.0.1:52304 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:41:52 - INFO - 127.0.0.1:52305 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:41:53 - INFO - 127.0.0.1:52310 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:46:15 - INFO - 127.0.0.1:52442 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:46:15 - INFO - 127.0.0.1:52443 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:46:15 - INFO - 127.0.0.1:52444 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:46:16 - INFO - 127.0.0.1:52447 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:50:33 - INFO - 127.0.0.1:52677 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:50:35 - INFO - 127.0.0.1:52684 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:52:19 - INFO - 127.0.0.1:52735 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:52:30 - INFO - 127.0.0.1:52742 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:52:31 - INFO - 127.0.0.1:52767 - "GET /api/v1/role/creatable HTTP/1.1" 200 OK
2025-08-11 14:52:32 - INFO - 127.0.0.1:52770 - "GET /api/v1/role/creatable HTTP/1.1" 200 OK
2025-08-11 14:52:32 - INFO - 127.0.0.1:52766 - "GET /api/v1/user/list?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:52:33 - INFO - 127.0.0.1:52769 - "GET /api/v1/user/agents?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:52:34 - INFO - 127.0.0.1:52773 - "GET /api/v1/role/creatable HTTP/1.1" 200 OK
2025-08-11 14:52:35 - INFO - 127.0.0.1:52772 - "GET /api/v1/user/list?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:52:38 - INFO - 127.0.0.1:52780 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:52:41 - INFO - 127.0.0.1:52783 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:52:46 - INFO - 127.0.0.1:52786 - "GET /api/v1/points/usage/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:52:52 - INFO - 127.0.0.1:52789 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:52:58 - INFO - 127.0.0.1:52793 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:52:59 - INFO - 127.0.0.1:52795 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:53:01 - INFO - 127.0.0.1:52797 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:53:04 - INFO - 127.0.0.1:52799 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:53:07 - INFO - 127.0.0.1:52811 - "GET /api/v1/role/creatable HTTP/1.1" 200 OK
2025-08-11 14:53:10 - INFO - 127.0.0.1:52810 - "GET /api/v1/user/agents?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:53:28 - INFO - 127.0.0.1:52825 - "POST /api/v1/user/add_points HTTP/1.1" 200 OK
2025-08-11 14:53:30 - INFO - 127.0.0.1:52827 - "GET /api/v1/user/agents?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:53:37 - INFO - 127.0.0.1:52835 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:53:41 - INFO - 127.0.0.1:52857 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:53:50 - INFO - 127.0.0.1:52873 - "GET /api/v1/points/usage/admin/records?page=1&size=20&usage_type=transfer_to_others HTTP/1.1" 200 OK
2025-08-11 14:53:55 - INFO - 127.0.0.1:52877 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:54:13 - INFO - 127.0.0.1:52883 - "GET /api/v1/role/creatable HTTP/1.1" 200 OK
2025-08-11 14:54:15 - INFO - 127.0.0.1:52882 - "GET /api/v1/user/agents?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:54:25 - INFO - 127.0.0.1:52891 - "POST /api/v1/user/add_points HTTP/1.1" 200 OK
2025-08-11 14:54:28 - INFO - 127.0.0.1:52893 - "GET /api/v1/user/agents?page=1&page_size=10 HTTP/1.1" 200 OK
2025-08-11 14:54:31 - INFO - 127.0.0.1:52899 - "GET /api/v1/points/info HTTP/1.1" 200 OK
2025-08-11 14:54:32 - INFO - 127.0.0.1:52901 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:54:38 - INFO - 127.0.0.1:52903 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:54:42 - INFO - 127.0.0.1:52911 - "GET /api/v1/base/userinfo HTTP/1.1" 200 OK
2025-08-11 14:54:42 - INFO - 127.0.0.1:52912 - "GET /api/v1/base/usermenu HTTP/1.1" 200 OK
2025-08-11 14:54:42 - INFO - 127.0.0.1:52913 - "GET /api/v1/base/userapi HTTP/1.1" 200 OK
2025-08-11 14:54:43 - INFO - 127.0.0.1:52916 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:54:46 - INFO - 127.0.0.1:52919 - "GET /api/v1/points/usage/admin/records?page=1&size=20&usage_type=transfer_to_others HTTP/1.1" 200 OK
2025-08-11 14:54:50 - INFO - 127.0.0.1:52921 - "GET /api/v1/points/usage/admin/records?page=1&size=20 HTTP/1.1" 200 OK
2025-08-11 14:57:06 - WARNING - WatchFiles detected changes in 'app/controllers/points.py'. Reloading...
2025-08-11 14:57:06 - INFO - Shutting down
2025-08-11 14:57:06 - INFO - Waiting for application shutdown.
2025-08-11 14:57:06 - INFO - Application shutdown complete.
2025-08-11 14:57:06 - INFO - Finished server process [32337]
2025-08-11 14:57:07 - INFO - Started server process [40109]
2025-08-11 14:57:07 - INFO - Waiting for application startup.
2025-08-11 14:57:07.435 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:57:07.435 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:57:07 - INFO - Application startup complete.
2025-08-11 14:57:26 - WARNING - WatchFiles detected changes in 'app/controllers/user.py'. Reloading...
2025-08-11 14:57:26 - INFO - Shutting down
2025-08-11 14:57:26 - INFO - Waiting for application shutdown.
2025-08-11 14:57:26 - INFO - Application shutdown complete.
2025-08-11 14:57:26 - INFO - Finished server process [40109]
2025-08-11 14:57:27 - INFO - Started server process [40316]
2025-08-11 14:57:27 - INFO - Waiting for application startup.
2025-08-11 14:57:27.186 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:57:27.186 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:57:27 - INFO - Application startup complete.
2025-08-11 14:57:47 - WARNING - WatchFiles detected changes in 'app/api/v1/users/users.py'. Reloading...
2025-08-11 14:57:47 - INFO - Shutting down
2025-08-11 14:57:47 - INFO - Waiting for application shutdown.
2025-08-11 14:57:47 - INFO - Application shutdown complete.
2025-08-11 14:57:47 - INFO - Finished server process [40316]
2025-08-11 14:57:48 - INFO - Started server process [40486]
2025-08-11 14:57:48 - INFO - Waiting for application startup.
2025-08-11 14:57:48.386 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:57:48.387 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:57:48 - INFO - Application startup complete.
2025-08-11 14:58:00 - WARNING - WatchFiles detected changes in 'app/api/v1/users/users.py'. Reloading...
2025-08-11 14:58:00 - INFO - Shutting down
2025-08-11 14:58:00 - INFO - Waiting for application shutdown.
2025-08-11 14:58:00 - INFO - Application shutdown complete.
2025-08-11 14:58:00 - INFO - Finished server process [40486]
2025-08-11 14:58:00 - INFO - Started server process [40573]
2025-08-11 14:58:00 - INFO - Waiting for application startup.
2025-08-11 14:58:00.935 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:58:00.935 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:58:01 - INFO - Application startup complete.
2025-08-11 14:58:24 - WARNING - WatchFiles detected changes in 'app/api/v1/users/users.py'. Reloading...
2025-08-11 14:58:24 - INFO - Shutting down
2025-08-11 14:58:24 - INFO - Waiting for application shutdown.
2025-08-11 14:58:24 - INFO - Application shutdown complete.
2025-08-11 14:58:24 - INFO - Finished server process [40573]
2025-08-11 14:58:25 - INFO - Started server process [40826]
2025-08-11 14:58:25 - INFO - Waiting for application startup.
2025-08-11 14:58:25.525 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:58:25.525 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:58:25 - INFO - Application startup complete.
2025-08-11 14:58:38 - WARNING - WatchFiles detected changes in 'app/api/v1/points/points.py'. Reloading...
2025-08-11 14:58:38 - INFO - Shutting down
2025-08-11 14:58:38 - INFO - Waiting for application shutdown.
2025-08-11 14:58:38 - INFO - Application shutdown complete.
2025-08-11 14:58:38 - INFO - Finished server process [40826]
2025-08-11 14:58:38 - INFO - Started server process [40913]
2025-08-11 14:58:38 - INFO - Waiting for application startup.
2025-08-11 14:58:39.005 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:58:39.005 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:58:39 - INFO - Application startup complete.
2025-08-11 14:58:56 - WARNING - WatchFiles detected changes in 'app/api/v1/points/points.py'. Reloading...
2025-08-11 14:58:56 - INFO - Shutting down
2025-08-11 14:58:56 - INFO - Waiting for application shutdown.
2025-08-11 14:58:56 - INFO - Application shutdown complete.
2025-08-11 14:58:56 - INFO - Finished server process [40913]
2025-08-11 14:58:56 - INFO - Started server process [41080]
2025-08-11 14:58:56 - INFO - Waiting for application startup.
2025-08-11 14:58:56.840 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 14:58:56.840 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 14:58:57 - INFO - Application startup complete.
2025-08-11 15:13:37 - WARNING - WatchFiles detected changes in 'tests/test_points_transfer_comprehensive.py'. Reloading...
2025-08-11 15:13:37 - INFO - Shutting down
2025-08-11 15:13:37 - INFO - Waiting for application shutdown.
2025-08-11 15:13:37 - INFO - Application shutdown complete.
2025-08-11 15:13:37 - INFO - Finished server process [41080]
2025-08-11 15:13:38 - INFO - Started server process [48573]
2025-08-11 15:13:38 - INFO - Waiting for application startup.
2025-08-11 15:13:38.114 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 15:13:38.114 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 15:13:38 - INFO - Application startup complete.
2025-08-11 15:14:18 - WARNING - WatchFiles detected changes in 'tests/test_points_transfer_api.py'. Reloading...
2025-08-11 15:14:18 - INFO - Shutting down
2025-08-11 15:14:19 - INFO - Waiting for application shutdown.
2025-08-11 15:14:19 - INFO - Application shutdown complete.
2025-08-11 15:14:19 - INFO - Finished server process [48573]
2025-08-11 15:14:19 - INFO - Started server process [48961]
2025-08-11 15:14:19 - INFO - Waiting for application startup.
2025-08-11 15:14:19.698 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 15:14:19.698 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 15:14:19 - INFO - Application startup complete.
2025-08-11 15:17:25 - WARNING - WatchFiles detected changes in 'tests/test_points_transfer_api.py'. Reloading...
2025-08-11 15:17:25 - INFO - Shutting down
2025-08-11 15:17:26 - INFO - Waiting for application shutdown.
2025-08-11 15:17:26 - INFO - Application shutdown complete.
2025-08-11 15:17:26 - INFO - Finished server process [48961]
2025-08-11 15:17:26 - INFO - Started server process [50735]
2025-08-11 15:17:26 - INFO - Waiting for application startup.
2025-08-11 15:17:26.569 | INFO     | app.core.init_app:init_db:189 - Tortoise ORM initialized successfully
2025-08-11 15:17:26.569 | INFO     | app.core.init_app:init_db:192 - Skipping database migration as fields already exist
2025-08-11 15:17:26 - INFO - Application startup complete.
